format = """
$os[](fg:7 bg:0)\
$username\
$hostname[](fg:0 bg:blue)\
$directory[](fg:blue bg:green)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status[](fg:green)\
$cmd_duration\
$line_break\
$jobs\
$battery\
$shell\
$character"""

[os]
style = 'bg:7 fg:232'
format = '[ $symbol]($style)'
disabled = false

[username]
style_user = "bg:0 fg:3"
style_root = "bg:0 fg:1"
format = '[ $user]($style)'

[hostname]
style = 'bg:0 fg:3'
format = '[@$hostname ]($style)'

[directory]
style = "fg:bold 254 bg:4"
format = "[ $path[$read_only]($read_only_style) ]($style)"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:green fg:0"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_commit]
style = "bg:green fg:0"
format = '[\($hash$tag\) ]($style)'

[git_state]
style = "bg:green fg:1"
format = '[$state( $progress_current/$progress_total) ]($style)'

[git_status]
style = "bg:green fg:1"
format = '[($all_status$ahead_behind )]($style)'

[cmd_duration]
format = ' [$duration]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
